data=read.csv("text.csv")
print(head(data,5))
print(summary(data))
cat("basic nalysis\n")
print(mean(data$ge,na.rm=TRUE))
print(median(data$ge,na.rm = TRUE))
a=as.numeric(names(sort(table(data$ge),decreasing =TRUE)[1]))
grn_tab<-table(data$gender)
print(grn_tab)
barplot(grn_tab,main="chart",col="lightblue")