val<-c(1,2,3,4,5)
prob<-c(0.1,0.2,0.3,0.2,0.2)
mv<-sum(val*prob)
cat("mean calculate",mv,"\n")
md<-median(rep(val,prob*100))
cat("median",md,"\n")
var<-sum((val-mv)^2*prob)
sd<-sqrt(var)
cat("stand deviation",sd,"\n")
